version: '3'

services:

  guacd:
    image: "guacamole/guacd"
    container_name: guacd

  postgres:
    image: "guac-postgres"
    environment:
      POSTGRES_PASSWORD: PASSWORD_HERE
    container_name: postgres
    volumes:
      - /tmp/init:/tmp

  guacamole:
    image: "guacamole/guacamole"
    depends_on:
      - guacd
      - postgres
    links:
      - guacd
      - postgres
    environment:
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: PASSWORD_HERE
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
    container_name: guacamole
    ports:
      - "8080:8080"
